In [2]:
import pandas as pd
import numpy as np
import scanpy as sc
import anndata

In [3]:
# change this to the directory that contains the datasets
data_dir = 'C:/Users/nbrouwer1/Documents/VS_projects/prepare_data/input_files/sciplex_processed/'

fn = data_dir + 'sciplex2_processed2.h5ad'

adata_orig = sc.read_h5ad(fn)
adata_orig

AnnData object with n_obs × n_vars = 20964 × 35653
    obs: 'i', 'n_counts', 'Size_Factor', 'drug', 'dose', 'count genes expressed', 'ratio mt2non_mt', 'treated_label'
    var: 'ensembl_id'

In [25]:
gene_medians = pd.read_pickle(r'./input_files/gene_median_dictionary.pkl')
gene_medians = pd.DataFrame.from_dict(gene_medians, orient='index')
gene_names = pd.read_pickle(r'./input_files/gene_name_id_dict.pkl')
gene_names = pd.DataFrame.from_dict(gene_names, orient='index')

gene_medians.to_csv('gene_medians.csv')

In [5]:
adata_orig.obs['treated_label'].unique()

['NAN', 'Dex', 'Nutlin', 'BMS', 'Untreated', 'SAHA']
Categories (6, object): ['BMS', 'Dex', 'NAN', 'Nutlin', 'SAHA', 'Untreated']

In [24]:
def difference(lst1, lst2):
    lst3 = [value for value in lst1 if value not in lst2]
    return lst3

sciplex_genes = pd.DataFrame(adata_orig.var['ensembl_id'].unique())
print(len(list(gene_names[0])))
print(len(list(sciplex_genes[0])))
diff  = difference(list(sciplex_genes[0]),list(gene_names[0]) )
print(len(diff))
print(diff)

40248
35653
9500
['ENSG00000067601', 'ENSG00000083622', 'ENSG00000093100', 'ENSG00000099251', 'ENSG00000100101', 'ENSG00000100181', 'ENSG00000106133', 'ENSG00000111780', 'ENSG00000111788', 'ENSG00000112096', 'ENSG00000116883', 'ENSG00000116957', 'ENSG00000120555', 'ENSG00000124549', 'ENSG00000124593', 'ENSG00000124835', 'ENSG00000125695', 'ENSG00000127957', 'ENSG00000128262', 'ENSG00000130723', 'ENSG00000131152', 'ENSG00000132832', 'ENSG00000133808', 'ENSG00000134030', 'ENSG00000141979', 'ENSG00000144785', 'ENSG00000145063', 'ENSG00000145075', 'ENSG00000146556', 'ENSG00000147324', 'ENSG00000149516', 'ENSG00000149656', 'ENSG00000151303', 'ENSG00000154198', 'ENSG00000154359', 'ENSG00000154874', 'ENSG00000159239', 'ENSG00000161149', 'ENSG00000161912', 'ENSG00000163009', 'ENSG00000163016', 'ENSG00000164825', 'ENSG00000165121', 'ENSG00000166104', 'ENSG00000167046', 'ENSG00000167774', 'ENSG00000167798', 'ENSG00000167807', 'ENSG00000167945', 'ENSG00000168255', 'ENSG00000170089', 'ENSG00000170

Some sciplex ensembl ids are not in the Geneformer gene set, but have the same gene symbol. Their location on the chromosome is different. Do we merge them or not?

In [4]:
XX2 = adata_orig.X.toarray()
adata =  anndata.AnnData(XX2,  obs=adata_orig.obs.copy(), 
                     var=adata_orig.var.copy() )

print(adata.X[:5,:5])

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]
